### ISSUE TITLE
Map loader fails on Windows

### ISSUE THREAD

**Issue by randomir** [dwave-examples/structural-imbalance#24]
```
Traceback (most recent call last):
  File "C:\Users\circleci\repo\demo.py", line 86, in <module>
    gssn = GlobalSignedSocialNetwork(qpu)
  File "C:\Users\circleci\repo\dwave_structural_imbalance_demo\interfaces.py", line 60, in __init__
    maps['Global'] = global_signed_social_network()
  File "C:\Users\circleci\repo\dwave_structural_imbalance_demo\mmp_network\loader.py", line 34, in global_signed_social_network
    next(data_iter)
  File "C:\Users\circleci\repo\python\tools\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6347: character maps to <undefined>
ETraceback (most recent call last):
  File "C:\Users\circleci\repo\demo.py", line 86, in <module>
    gssn = GlobalSignedSocialNetwork(qpu)
  File "C:\Users\circleci\repo\dwave_structural_imbalance_demo\interfaces.py", line 60, in __init__
    maps['Global'] = global_signed_social_network()
  File "C:\Users\circleci\repo\dwave_structural_imbalance_demo\mmp_network\loader.py", line 34, in global_signed_social_network
    next(data_iter)
  File "C:\Users\circleci\repo\python\tools\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6347: character maps to <undefined>
```

**Comment by arcondello** [comment]
https://github.com/dwave-examples/structural-imbalance/commit/60b2fc35e06c5e6e7fd0b31d7673978e9ec1d32b fixes the loader, but now the tests are failing for other reasons
